#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from edgar_filing_pipeline.workflow import normalize_from_manifest, read_manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Normalize EDGAR segments into text + markdown tables.")
    parser.add_argument("--manifest", type=Path, required=True, help="Parquet/CSV manifest generated by build_manifest.py")
    parser.add_argument("--tar-root", type=Path, required=True, help="Directory containing the raw .nc.tar.gz archives")
    parser.add_argument("--output", type=Path, required=True, help="Destination Parquet file for normalized segments")
    parser.add_argument("--limit", type=int, help="Optional limit on the number of segments to process")
    args = parser.parse_args()

    manifest = read_manifest(args.manifest)

    normalized_df = normalize_from_manifest(
        manifest,
        tar_root=args.tar_root,
        limit=args.limit,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    normalized_df.to_parquet(args.output, index=False)

    print(
        json.dumps(
            {
                "segments_processed": len(normalized_df),
                "output_path": str(args.output),
                "total_tables": int(normalized_df["num_tables"].sum()),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
